### ISSUE TITLE
bf_sources_grid calls missing FieldTrip subfunction 

### ISSUE THREAD

**Issue by georgeoneill** [spm/DAiSS#2]
I stumbled across an error where DAiSS was calling a subroutine in FieldTrip to check which source locations exist inside the inner skull region in line 110:

`inside = ft_inside_headmodel(pos, struct('bnd', constraint));`

However, a clean install of SPM12 (v7487) this function is not included in the $SPMROOT/external/fieldtrip folder, but _ft_inside_vol_ is. Is it worth having a try/catch statement here or replacing the required function perhaps?

**Comment by robertoostenveld** [comment]
As background: The function `ft_inside_vol` was renamed to `ft_inside_headmodel` around Feb 2019. In the regular fieldtrip release  `ft_inside_vol` is still present (in the forward directory); its gives a warning and then calls `ft_inside_headmodel`.

I don't know how the SPM versions are aligned with FieldTrip versions. To keep new SPM code working with old FT code, a try-catch around the specific call would be appropriate.

Note that ideally all use of FT functions by SPM should be part of https://github.com/fieldtrip/fieldtrip/blob/master/test/test_spm_ft_integration.m. This ensures that we detect it as error in case we make a change to the function names or API. The `ft_inside_vol` is not in that test script, hence its change breaking something went undetected.

**Comment by georgeoneill** [comment]
Thanks Robert. I'll discuss this with some of the DAiSS maintainers at the FIL.

**Comment by vlitvak** [comment]
I suspect this has something to do with the path not being set correctly. Make sure you run 'spm eeg'  or spm('defaults', 'eeg') before running DAiSS.
